In [234]:
import numpy as np
import pandas as pd

In [235]:
problem = pd.read_csv('transportation.csv', header=None)
problem = problem.to_numpy()
print(problem)
costs = problem[:-1, :-1]
cost_matrix = costs
supply = problem[:-1, -1]
demand = problem[-1, :-1]

print("cost_matrix:",cost_matrix)
print("supply:",supply)
print("demand:",demand)
print("cost_matrix.shape:",cost_matrix.shape)

[[19. 30. 50. 10.  7.]
 [70. 30. 40. 60.  9.]
 [40.  8. 70. 20. 18.]
 [ 5.  8.  7. 14. nan]]
cost_matrix: [[19. 30. 50. 10.]
 [70. 30. 40. 60.]
 [40.  8. 70. 20.]]
supply: [ 7.  9. 18.]
demand: [ 5.  8.  7. 14.]
cost_matrix.shape: (3, 4)


In [236]:
#VAM
rowPenalty = np.zeros(cost_matrix.shape[0])
colPenalty = np.zeros(cost_matrix.shape[1])

print("initial rowPenalty:",rowPenalty)
print("initial colPenalty:",colPenalty)

assignments = np.zeros(cost_matrix.shape)
total_cost = 0
cost_list = []
for i in range(10):
    
    if (np.sum(supply) == 0 and np.sum(demand) == 0 or supply.shape[0] == 0 or demand.shape[0] == 0):
        print("all supply and demand are zero")
        print("total cost:",total_cost)
        break

    rowPenalty = np.zeros(cost_matrix.shape[0])
    colPenalty = np.zeros(cost_matrix.shape[1])

    print("\n\niteration:",i)
    print(cost_list)
    temp_matrix = cost_matrix

    print("temp_matrix:\n",temp_matrix)

    for i in range(cost_matrix.shape[0]):
        sorted_arr = np.sort(temp_matrix[i])
        min_val = sorted_arr[0]
        sec_min_val = sorted_arr[1]
        diff = sec_min_val - min_val
        rowPenalty[i] = diff
    for i in range(temp_matrix.shape[1]):
        sorted_arr = np.sort(temp_matrix[:,i])
        min_val = sorted_arr[0]
        sec_min_val = sorted_arr[1]
        diff = sec_min_val - min_val
        colPenalty[i] = diff
    print("rowPenalty:\n",rowPenalty)
    print("colPenalty:\n",colPenalty)
    print("initial cost_matrix:\n",cost_matrix)
    
    max_row_penalty_index = None
    max_col_penalty_index = None

    max_penalty = max(rowPenalty)

    if(max_penalty < max(colPenalty)):
        max_penalty = max(colPenalty)
        max_col_penalty_index = np.argmax(colPenalty)
    else:
        max_row_penalty_index = np.argmax(rowPenalty)

    if(max_row_penalty_index != None):
        row = max_row_penalty_index
        col = np.argmin(cost_matrix[row])
        print("row and col:",row,col)
        # assignments[row][col] = min(supply[row],demand[col])
        newAssignment = min(supply[row],demand[col])
        # newAssignment = newAssignment[0]
        print("the new assignment:",newAssignment)
        print("type of newAssignment (row):",type(newAssignment))
        supply[row] -= newAssignment
        demand[col] -= newAssignment
        total_cost += cost_matrix[row][col] * newAssignment
        print("assigned value:\n",cost_matrix[row][col],"->",newAssignment)
        cost_list.append((cost_matrix[row][col],newAssignment))        
        print("supply:\n",supply)
        print("demand:\n",demand)
        # print("assignments:\n",assignments)
        print("cost_matrix:\n",cost_matrix)

    elif(max_col_penalty_index != None):
        col = max_col_penalty_index
        row = np.argmin(cost_matrix[:,col])
        print("row and col:",row,col)
        # assignments[row][col] = min(supply[row],demand[col])
        newAssignment = min(supply[row],demand[col])
        # print("the new assignment:",newAssignment)
        print("type of newAssignment (col):",type(newAssignment))
        print("assigned value:\n",cost_matrix[row][col],"->",newAssignment)
        cost_list.append((cost_matrix[row][col],newAssignment)) 
        total_cost += cost_matrix[row][col] * newAssignment
        supply[row] -= newAssignment
        demand[col] -= newAssignment
        print("supply:\n",supply)
        print("demand:\n",demand)
        # print("assignments:\n",assignments)
        print("cost_matrix:\n",cost_matrix)
    # check if supply is zero
    for i in range(supply.shape[0]):
        # print("checking supply",supply[i])
        print("supply.shape[0]:",supply.shape[0])
        if supply.shape[0] == 1:
            if supply[0] == 0:
                break
            else:
                for cost in cost_matrix:
                    print("cost:",cost)
                    print("demand:",demand)
                    for i in range(len(cost)):
                        newAssignment = demand[i]
                        print("newAssignment:",newAssignment)
                        total_cost += cost[i] * newAssignment
                        print("total_cost:",total_cost)
                        cost_list.append((cost[i],newAssignment))
                
                    
                    
                supply = np.delete(supply, i-1, 0)
                break
        else:
            if(supply[i] == 0):
                print("supply is zero at index:\n",i)
                cost_matrix = np.delete(cost_matrix, i, 0)
                supply = np.delete(supply, i, 0)
                print("new cost_matrix:\n",cost_matrix)
                print("new supply:\n",supply)
                print("new demand:",demand)
        
            
    # # check if demand is zero
    # print(len(demand))
    for i in range(demand.shape[0]-1):
        if demand.shape[0] == 1:
            if demand[0] == 0:
                break
            else:
                for cost in range(len(cost_matrix)):
                    print("cost:",cost_matrix[cost])
                    print("supply:",supply)
                    for i in range(len(cost)):
                        newAssignment = supply[i]
                        print("newAssignment:",newAssignment)
                        total_cost += cost[i] * newAssignment
                        print("total_cost:",total_cost)
                        cost_list.append((cost[i],newAssignment))
                break
        else:
            if(demand[i] == 0):
                print("demand is zero at index:\n",i)
                cost_matrix = np.delete(cost_matrix, i, 1)
                demand = np.delete(demand, i, 0)
                print("new cost_matrix:\n",cost_matrix)
                print("new supply:\n",supply)
                print("new demand:",demand)
        
        
    
print("total_cost:",total_cost)

    # if(max_row_penalty_index != None):
    #     row = max_row_penalty_index
    #     col = np.argmin(cost_matrix[row])
    # print("max_penalty:",max_col_penalty_index)


initial rowPenalty: [0. 0. 0.]
initial colPenalty: [0. 0. 0. 0.]


iteration: 0
[]
temp_matrix:
 [[19. 30. 50. 10.]
 [70. 30. 40. 60.]
 [40.  8. 70. 20.]]
rowPenalty:
 [ 9. 10. 12.]
colPenalty:
 [21. 22. 10. 10.]
initial cost_matrix:
 [[19. 30. 50. 10.]
 [70. 30. 40. 60.]
 [40.  8. 70. 20.]]
row and col: 2 1
type of newAssignment (col): <class 'numpy.float64'>
assigned value:
 8.0 -> 8.0
supply:
 [ 7.  9. 10.]
demand:
 [ 5.  0.  7. 14.]
cost_matrix:
 [[19. 30. 50. 10.]
 [70. 30. 40. 60.]
 [40.  8. 70. 20.]]
supply.shape[0]: 3
supply.shape[0]: 3
supply.shape[0]: 3
demand is zero at index:
 1
new cost_matrix:
 [[19. 50. 10.]
 [70. 40. 60.]
 [40. 70. 20.]]
new supply:
 [ 7.  9. 10.]
new demand: [ 5.  7. 14.]


iteration: 1
[(8.0, 8.0)]
temp_matrix:
 [[19. 50. 10.]
 [70. 40. 60.]
 [40. 70. 20.]]
rowPenalty:
 [ 9. 20. 20.]
colPenalty:
 [21. 10. 10.]
initial cost_matrix:
 [[19. 50. 10.]
 [70. 40. 60.]
 [40. 70. 20.]]
row and col: 0 0
type of newAssignment (col): <class 'numpy.float64'>
assig